### ISSUE TITLE
Add a pre-register button that adds email to email list

### ISSUE THREAD

**Issue by geooot** [tamu-datathon-org/gigabowser#136]
We want to add a pre-register button that goes to MailChimp (adds them to MailChimp list which we send email later when registration opens)

This is open for discussion (implementation, mail provider, etc)

**Comment by danielabreo** [comment]
Currently planning on changing the 'Apply' button to 'Get Updates' and then on click either:

1. open the current mail chimp form () in a new tab since adding a new contact to the main contact list can include info like full name, DOB, and university

2. make an email input box + submit button combo appear below the buttons with placeholder text "Join our mailing list (to be notified with applications open)" which would be faster for users, but only collect their email

**Comment by geooot** [comment]
@danielabreo
- "Get Updates" sounds a bit too vague for me. Maybe "Get Notified" or something?
- I think popping a modal would be better then just having a form appear. But I'm okay with the new tab thing as well
