### ISSUE TITLE
Industry Section Modal

### ISSUE THREAD

**Issue by geooot** [tamu-datathon-org/gigabowser#53]
Create a modal (that appears on icon click) that shows a small two-sentence description, the icon itself, a side-nav thing that lets the user switch to other industries, and a list of sponsors that are associated with the industry.

- Make sure to keep the code for this pretty modular
   - Create the pages.js variables and such
- Allow us to just add a class like `triggerModal` and an attribute like `industry-id="someIdThatWouldPointToAnIndustry"` to an element to let us trigger the industry modal.

**Comment by phulsechinmay** [comment]
@geooot Could use some help with making the sponsor image list for the industry modals. I'm thinking we can do a horizontal list similar to what we have for the sponsor section on mobile. Do you have the bandwidth to correct the css for that because I've been working on it for a bit and can't get it right. 

Branch is `industry-modal`.

**Comment by geooot** [comment]
Ill take a look

**Comment by geooot** [comment]
@phulsechinmay I've added some changes to make the modal look better and I fixed the carousel.
